### ISSUE TITLE
torch.load raise ModuleNotFoundError: No module named 'DeepRobust'

### ISSUE THREAD

**Issue by ToTDream** [DSE-MSU/DeepRobust#29]

**Comment by ChandlerBang** [comment]
Could you provide more details about the problem you met? Maybe you can copy your code so we can reproduce the problem.

**Comment by ToTDream** [comment]
Sorry. I just run the Test Examples.

> $ python examples/image/test_PGD.py
Load network
Traceback (most recent call last):
  File "examples/image/test_PGD.py", line 18, in <module>    
    model.load_state_dict(torch.load("./trained_models/CIFAR10_ResNet18_epoch_50.pt"))
  File "C:\Users\hasee\Anaconda3\envs\python36\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\hasee\Anaconda3\envs\python36\lib\site-packages\torch\serialization.py", line 773, in _legacy_load       
    result = unpickler.load()
ModuleNotFoundError: No module named 'DeepRobust'


And I also wonder why it has something to do with “DeepRobust”. Maybe I didn’t install it successfully? Thank you for your attention!

**Comment by ToTDream** [comment]
Thank you so much!
