### ISSUE TITLE
test_gat.py throwing error when running: "AttributeError: 'GATConv' object has no attribute 'weight'"

### ISSUE THREAD

**Issue by satvikchekuri** [DSE-MSU/DeepRobust#57]
When running the following python program test_gat.py, it is throwing an error as below.

Traceback (most recent call last):
  File "test_gat.py", line 34, in <module>
    gat.fit(pyg_data, verbose=True) # train with earlystopping
  File "/home/satvikchekuri/anaconda3/envs/graph/lib/python3.8/site-packages/deeprobust-0.2.0-py3.8.egg/deeprobust/graph/defense/gat.py", line 123, in fit
  File "/home/satvikchekuri/anaconda3/envs/graph/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
**AttributeError: 'GATConv' object has no attribute 'weight'**

**Comment by ChandlerBang** [comment]
Hi,

It seems that GATConv in the newest pyg  has changed the parameter "weight" to "lin_l.weight".  I have just fixed the issue and updated the code. Please see commit 85f59b6db65732fcdbea1b7a8e5c769f2b41ebbf. 

Thanks for bring this up!
